[device_profiles]
GPU-75f6d20c-3cea-093e-c165-0185a79f3e86 = "myProfile"

[profile_configs.myProfile]
fan_mode = "Curve"
fan_curve = "myCurve"

[profile_configs.myProfile.device_config.vendor_config.Nvidia]

[profile_configs.myProfile.fan_update_interval]
secs = 3
nanos = 0

[profile_configs.myProfile.data_update_interval]
secs = 1
nanos = 0

[fan_curve_configs.myCurve]
points = [
    [
    40,
    40,
],
    [
    50,
    50,
],
    [
    60,
    80,
],
    [
    75,
    100,
],
]
lower_threshold = 3
upper_threshold = 2
